/**
 * ================== Dashboard tasks ================================
 */

export const FETCH_ERROR_RATE = "FETCH_ERROR_RATE";
export const FETCH_ERROR_RATE_SUCCESS = "FETCH_ERROR_RATE_SUCCESS";
export const FETCH_ERROR_RATE_FAILED = "FETCH_ERROR_RATE_FAILED";

export const FETCH_LATENCY = "FETCH_LATENCY";
export const FETCH_LATENCY_SUCCESS = "FETCH_LATENCY_SUCCESS";
export const FETCH_LATENCY_FAILED = "FETCH_LATENCY_FAILED";

export const FETCH_TOTAL_USERS = "FETCH_TOTAL_USERS";
export const FETCH_TOTAL_USERS_SUCCESS = "FETCH_TOTAL_USERS_SUCCESS";
export const FETCH_TOTAL_USERS_FAILED = "FETCH_TOTAL_USERS_FAILED";

export const FETCH_ERROR_BUDGET = "FETCH_ERROR_BUDGET";
export const FETCH_ERROR_BUDGET_SUCCESS = "FETCH_ERROR_BUDGET_SUCCESS";
export const FETCH_ERROR_BUDGET_FAILED = "FETCH_ERROR_BUDGET_FAILED";

export const FETCH_JIRA_TICKETS = "FETCH_JIRA_TICKETS";
export const FETCH_JIRA_TICKETS_SUCCESS = "FETCH_JIRA_TICKETS_SUCCESS";
export const FETCH_JIRA_TICKETS_FAILED = "FETCH_JIRA_TICKETS_FAILED";
export const CHANGE_JIRA_TICKET_FILTER = "CHANGE_JIRA_TICKET_FILTER";
export const CHANGE_JIRA_TOCKET_CREATED_DATE = "CHANGE_JIRA_CREATED_DATE";
export const CHANGE_JIRA_TICKET_STATUS = "CHANGE_JIRA_TICKET_STATUS";
export const CHANGE_JIRA_TICKET_ROWS_PER_PAGE =
  "CHANGE_JIRA_TICKET_ROWS_PER_PAGE";

export const FETCH_RECENT_DEPLOYMENTS = "FETCH_RECENT_DEPLOYMENTS";
export const FETCH_RECENT_DEPLOYMENTS_SUCCESS =
  "FETCH_RECENT_DEPLOYMENTS_SUCCESS";
export const FETCH_RECENT_DEPLOYMENTS_FAILED =
  "FETCH_RECENT_DEPLOYMENTS_FAILED";
export const CHANGE_RECENT_DEPLOYMENTS_DURATION =
  "CHANGE_RECENT_DEPLOYMENTS_DURATION";

export const FETCH_CLIENT_MSR = "FETCH_CLIENT_MSR";
export const FETCH_CLIENT_MSR_SUCCESS = "FETCH_CLIENT_MSR_SUCCESS";
export const FETCH_CLIENT_MSR_FAILED = "FETCH_CLIENT_MSR_FAILED";
export const CHANGE_CLIENT_MSR_DAYS = "CHANGE_CLIENT_MSR_DAYS";

export const FETCH_SDK_MSR = "FETCH_SDK_MSR";
export const FETCH_SDK_MSR_SUCCESS = "FETCH_SDK_MSR_SUCCESS";
export const FETCH_SDK_MSR_FAILED = "FETCH_SDK_MSR_FAILED";
/**
 * ================== Dashboard tasks ends ============================
 */

/**
 * ================== SignIn Tasks ============================
 */
export const SET_USER_INFORMATION = "SET_USER_INFORMATION";
export const FETCH_GOOGLE_PROFILE = "FETCH_GOOGLE_PROFILE";
export const FETCH_GOOGLE_PROFILE_SUCCESS = "FETCH_GOOGLE_PROFILE_SUCCESS";
export const FETCH_GOOGLE_PROFILE_FAILED = "FETCH_GOOGLE_PROFILE_FAILED";
/**
 * ================== SignIn Tasks Ends ============================
 */

/**
 * ================== SLO Tasks ============================
 */
export const FETCH_SLO_FILTERS = "FETCH_SLO_FILTERS";
export const FETCH_SLO_FILTERS_SUCCESS = "FETCH_SLO_FILTERS_SUCCESS";
export const FETCH_SLO_FILTERS_FAILED = "FETCH_SLO_FILTERS_FAILED";

export const SET_SLO_TYPE = "SET_SLO_TYPE";
export const SET_SLO_SERVICE_TYPE = "SET_SERVICE_TYPE";
export const SET_SLO_TIME_RANGE = "SET_TIME_RANGE";
export const SET_SLO_TIME_FORMAT = "SET_TIME_FORMAT";
export const SET_SLO_TIME = "SET_SLO_TIME";
export const SET_SLO_RELATIVE_TIME = "SET_SLO_RELATIVE_TIME";

export const FETCH_SLO_GRAPH_DATA = "FETCH_SLO_GRAPH_DATA";
export const FETCH_SLO_GRAPH_DATA_SUCCESS = "FETCH_SLO_GRAPH_DATA_SUCCESS";
export const FETCH_SLO_GRAPH_DATA_FAILED = "FETCH_SLO_GRAPH_DATA_FAILED";
/**
 * ================== SLO Tasks Ends ============================
 */
