/**
 * ================== Dashboard tasks ================================
 */

export const FETCH_ERROR_RATE = "FETCH_ERROR_RATE";
export const FETCH_ERROR_RATE_SUCCESS = "FETCH_ERROR_RATE_SUCCESS";
export const FETCH_ERROR_RATE_FAILED = "FETCH_ERROR_RATE_FAILED";

export const FETCH_LATENCY = "FETCH_LATENCY";
export const FETCH_LATENCY_SUCCESS = "FETCH_LATENCY_SUCCESS";
export const FETCH_LATENCY_FAILED = "FETCH_LATENCY_FAILED";

export const FETCH_TOTAL_USERS = "FETCH_TOTAL_USERS";
export const FETCH_TOTAL_USERS_SUCCESS = "FETCH_TOTAL_USERS_SUCCESS";
export const FETCH_TOTAL_USERS_FAILED = "FETCH_TOTAL_USERS_FAILED";

export const FETCH_ERROR_BUDGET = "FETCH_ERROR_BUDGET";
export const FETCH_ERROR_BUDGET_SUCCESS = "FETCH_ERROR_BUDGET_SUCCESS";
export const FETCH_ERROR_BUDGET_FAILED = "FETCH_ERROR_BUDGET_FAILED";

export const FETCH_JIRA_TICKETS = "FETCH_JIRA_TICKETS";
export const FETCH_JIRA_TICKETS_SUCCESS = "FETCH_JIRA_TICKETS_SUCCESS";
export const FETCH_JIRA_TICKETS_FAILED = "FETCH_JIRA_TICKETS_FAILED";
export const CHANGE_JIRA_TICKET_FILTER = "CHANGE_JIRA_TICKET_FILTER";
export const CHANGE_JIRA_TOCKET_CREATED_DATE = "CHANGE_JIRA_CREATED_DATE";
export const CHANGE_JIRA_TICKET_STATUS = "CHANGE_JIRA_TICKET_STATUS";
export const CHANGE_JIRA_TICKET_ROWS_PER_PAGE =
  "CHANGE_JIRA_TICKET_ROWS_PER_PAGE";

export const FETCH_RECENT_DEPLOYMENTS = "FETCH_RECENT_DEPLOYMENTS";
export const FETCH_RECENT_DEPLOYMENTS_SUCCESS =
  "FETCH_RECENT_DEPLOYMENTS_SUCCESS";
export const FETCH_RECENT_DEPLOYMENTS_FAILED =
  "FETCH_RECENT_DEPLOYMENTS_FAILED";
export const CHANGE_RECENT_DEPLOYMENTS_DURATION =
  "CHANGE_RECENT_DEPLOYMENTS_DURATION";

/**
 * ================== Dashboard tasks ends ============================
 */
